name: Qt6 Android CI (Windows Stable)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      QT_VERSION: "6.6.3"
      NDK_VERSION: "26.1.10909125"
      ANDROID_API_LEVEL: "34"

    steps:
      - uses: actions/checkout@v4

      # 1. 安装NDK（精确版本）
      - name: Install NDK
        run: |
          $ndkUrl = "https://dl.google.com/android/repository/android-ndk-r26b-windows.zip"
          Invoke-WebRequest -Uri $ndkUrl -OutFile "ndk.zip"
          Expand-Archive -Path "ndk.zip" -DestinationPath "$env:GITHUB_WORKSPACE\android-sdk\ndk"
          Rename-Item "$env:GITHUB_WORKSPACE\android-sdk\ndk\android-ndk-r26b" "$env:GITHUB_WORKSPACE\android-sdk\ndk\$env:NDK_VERSION"
          echo "ANDROID_NDK_ROOT=$env:GITHUB_WORKSPACE\android-sdk\ndk\$env:NDK_VERSION" >> $env:GITHUB_ENV

      # 2. 安装Qt（关键修改：显式安装jom）
      - name: Install Qt with jom
        run: |
          # 先安装aqt工具
          python -m pip install aqtinstall
          # 安装Qt时强制包含jom
          aqt install-qt windows android ${{ env.QT_VERSION }} ${{ env.QT_ARCH }} -m qt5compat --tools ifw jom
          # 获取实际安装路径
          $qtPath = (Get-ChildItem "C:\Qt" -Filter "${{ env.QT_VERSION }}" -Recurse -Directory | Where-Object { $_.FullName -match "android" } | Select-Object -First 1).FullName
          echo "QT_PATH=$qtPath" >> $env:GITHUB_ENV
          echo "$qtPath\bin;C:\Qt\Tools\jom" >> $env:GITHUB_PATH

      # 3. 验证工具链
      - name: Verify Tools
        run: |
          where qmake
          where jom
          qmake --version
          jom --version || echo "::warning::jom not found, will use nmake"

      # 4. 智能构建（自动选择jom或nmake）
      - name: Build
        shell: cmd
        run: |
          qmake Knot.pro -spec android-clang CONFIG+=release ANDROID_ABIS=arm64-v8a

          if exist "C:\Qt\Tools\jom\jom.exe" (
            echo "Using jom..."
            C:\Qt\Tools\jom\jom.exe -j %NUMBER_OF_PROCESSORS%
            C:\Qt\Tools\jom\jom.exe apk INSTALL_ROOT=build
          ) else (
            echo "Using nmake..."
            nmake
            nmake apk INSTALL_ROOT=build
          )

      # 5. 上传产物
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Knot-APK
          path: build\android-build\build\outputs\apk\release\*.apk
