name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  QT_VERSION: 6.6.3
  ANDROID_API_LEVEL: 34
  BUILD_TOOLS_VERSION: 34.0.0
  NDK_VERSION: 25.1.8937393
  QT_DESKTOP_ARCH: win64_mingw  # 修正为 mingw 架构
  QT_ARCH: android_arm64_v8a

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: .  # 直接检出到工作目录根路径
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    # 安装 Android SDK/NDK
    - name: Setup Android SDK and NDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: ${{ env.NDK_VERSION }}
        sdk-version: ${{ env.ANDROID_API_LEVEL }}

    - name: Set Android Environment Variables
      shell: cmd
      run: |
        :: 硬编码 NDK 路径避免拼接错误
        echo ANDROID_NDK_ROOT=C:\Android\android-sdk\ndk\$env:NDK_VERSION >> %GITHUB_ENV%
        echo ANDROID_SDK_ROOT=C:\Android\android-sdk >> %GITHUB_ENV%

    - name: Install Qt Desktop
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        target: desktop
        arch: ${{ env.QT_DESKTOP_ARCH }}
        modules: qtcharts qtsensors qtlocation qtpositioning qt5compat

    - name: Install Qt Android
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        target: android
        arch: ${{ env.QT_ARCH }}
        modules: qtcharts qtsensors qtlocation qtpositioning qt5compat

    - name: Setup Toolchain Paths
      shell: cmd
      run: |
        :: 添加 Qt 和 MinGW 工具链到 PATH
        echo D:\a\Knot6\Qt\Tools\mingw1120_64\bin >> %GITHUB_PATH%
        echo D:\a\Knot6\Qt\6.6.3\android_arm64_v8a\bin >> %GITHUB_PATH%
        echo D:\a\Knot6\Qt\Tools\jom >> %GITHUB_PATH%

    - name: Build APK
      shell: cmd
      run: |
        :: 生成 Makefile（显式指定 NDK 路径）
        qmake.bat Knot.pro ^
          -spec android-clang ^
          "ANDROID_NDK_ROOT=%ANDROID_NDK_ROOT%" ^
          CONFIG+=release ^
          ANDROID_ABIS=arm64-v8a

        :: 并行编译
        jom -j4 || make -j4

        :: 生成 APK（指定输出目录）
        make apk ANDROID_APK_DIR=%CD%\build

    - name: Sign APK
      shell: cmd
      run: |
        :: 使用绝对路径避免混淆
        jarsigner -verbose ^
          -sigalg SHA256withRSA ^
          -digestalg SHA-256 ^
          -keystore android/app/my-release-key.keystore ^
          -storepass ${{ secrets.KEY_STORE_PASSWORD }} ^
          -keypass ${{ secrets.KEY_PASSWORD }} ^
          build\android-build-release-unsigned.apk ^
          ${{ secrets.KEY_ALIAS }}

        :: 使用 zipalign 优化 APK
        "%ANDROID_SDK_ROOT%\build-tools\%BUILD_TOOLS_VERSION%\zipalign" -v 4 ^
          build\android-build-release-unsigned.apk ^
          Knot6-release.apk

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Android-APK
        path: Knot6-release.apk
