name: Qt6 Android Build (Linux Fix)

env:
  QT_VERSION: "6.6.3"
  NDK_VERSION: "26.3.11579264"
  ANDROID_API_LEVEL: "34"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 安装 NDK 26（官方原版）
      - name: Install NDK 26
        uses: android-actions/setup-android@v3
        with:
          ndk-version: ${{ env.NDK_VERSION }}

      # 关键步骤：修复 Linux 的头文件路径
      - name: Fix NDK headers for Linux
        run: |
          NDK_SYSROOT=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot
          # 确保目标目录存在
          mkdir -p $NDK_SYSROOT/usr/include/bits
          # 复制所有必要头文件
          cp -r $NDK_SYSROOT/usr/include/aarch64-linux-android/bits/* $NDK_SYSROOT/usr/include/bits/

      # 验证修复是否成功
      - name: Check headers
        run: |
          ls -la $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/bits/libc-header-start.h
          if [ ! -f "$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/bits/libc-header-start.h" ]; then
            echo "::error::头文件修复失败！"
            exit 1
          fi

      # 构建时显式指定路径
      - name: Build with fixed paths
        run: |
          qmake Knot.pro \
            -spec android-clang \
            CONFIG+=release \
            ANDROID_ABIS=arm64-v8a \
            QMAKE_CFLAGS="-I$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aarch64-linux-android" \
            QMAKE_CXXFLAGS="$QMAKE_CFLAGS"

          make -j$(nproc) && make apk
