name: Build and Sign Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  QT_VERSION: "6.6.3"
  QT_ARCH: "android_arm64_v8a"
  ANDROID_API_LEVEL: "34"
  NDK_VERSION: "26.3.11579264"
  BUILD_TOOLS_VERSION: "34.0.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgl1-mesa-dev unzip

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android NDK
        run: |
          mkdir -p android-sdk/ndk
          wget https://dl.google.com/android/repository/android-ndk-r26b-linux.zip
          unzip -q android-ndk-r26b-linux.zip -d android-sdk/ndk/
          mv android-sdk/ndk/android-ndk-r26b android-sdk/ndk/${{ env.NDK_VERSION }}
          echo "ANDROID_SDK_ROOT=$GITHUB_WORKSPACE/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$GITHUB_WORKSPACE/android-sdk/ndk/${{ env.NDK_VERSION }}" >> $GITHUB_ENV

      - name: Verify NDK headers
        run: |
          echo "Checking NDK headers..."
          ls -la $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/
          ls -la $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/bits/

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          target: android
          arch: ${{ env.QT_ARCH }}
          modules: qt5compat qtcharts qtsensors qtlocation qtpositioning qtwebview

      - name: Configure project
        run: |
          TOOLCHAIN_PATH="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64"

          qmake Knot.pro \
            -spec android-clang \
            CONFIG+=release \
            ANDROID_ABIS=arm64-v8a \
            ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT \
            ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT \
            QMAKE_CC=$TOOLCHAIN_PATH/bin/aarch64-linux-android$ANDROID_API_LEVEL-clang \
            QMAKE_CXX=$TOOLCHAIN_PATH/bin/aarch64-linux-android$ANDROID_API_LEVEL-clang++ \
            ANDROID_MIN_SDK_VERSION=$ANDROID_API_LEVEL

      - name: Build project
        run: |
          make -j$(nproc)
          make apk INSTALL_ROOT=build

      - name: Prepare signing
        run: |
          mkdir -p signing
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > signing/app.keystore
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" > signing/keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> signing/keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> signing/keystore.properties
          echo "storeFile=../app.keystore" >> signing/keystore.properties

      - name: Sign APK
        if: ${{ secrets.KEY_STORE_PASSWORD != '' }}
        run: |
          cd signing
          jarsigner -verbose \
            -sigalg SHA256withRSA \
            -digestalg SHA-256 \
            -keystore app.keystore \
            -storepass "${{ secrets.KEY_STORE_PASSWORD }}" \
            -keypass "${{ secrets.KEY_PASSWORD }}" \
            ../build/android-build/build/outputs/apk/release/android-build-release-unsigned.apk \
            "${{ secrets.KEY_ALIAS }}"

          $ANDROID_SDK_ROOT/build-tools/$BUILD_TOOLS_VERSION/zipalign -v 4 \
            ../build/android-build/build/outputs/apk/release/android-build-release-unsigned.apk \
            ../app-release.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: app-release.apk
