name: Build and Sign Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  QT_VERSION: "6.6.3"
  QT_ARCH: "android_arm64_v8a"
  ANDROID_API_LEVEL: "34"
  NDK_VERSION: "26.3.11579264"
  BUILD_TOOLS_VERSION: "34.0.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgl1-mesa-dev unzip

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 关键修改：使用官方推荐的NDK安装方式
      - name: Install Android NDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: ${{ env.NDK_VERSION }}
          ndk-path: ${{ github.workspace }}/android-sdk/ndk/${{ env.NDK_VERSION }}

      - name: Verify NDK installation
        run: |
          echo "NDK path: ${{ github.workspace }}/android-sdk/ndk/${{ env.NDK_VERSION }}"
          echo "Sysroot path: ${{ github.workspace }}/android-sdk/ndk/${{ env.NDK_VERSION }}/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
          ls -la ${{ github.workspace }}/android-sdk/ndk/${{ env.NDK_VERSION }}/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/bits/

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          target: android
          arch: ${{ env.QT_ARCH }}
          modules: qt5compat qtcharts qtsensors qtlocation qtpositioning qtwebview

      - name: Configure project
        run: |
          # 设置环境变量
          echo "ANDROID_NDK_ROOT=${{ github.workspace }}/android-sdk/ndk/${{ env.NDK_VERSION }}" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=${{ github.workspace }}/android-sdk" >> $GITHUB_ENV

          # 使用Qt自动配置的工具链
          qmake Knot.pro \
            -spec android-clang \
            CONFIG+=release \
            ANDROID_ABIS=arm64-v8a \
            ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT \
            ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT \
            ANDROID_MIN_SDK_VERSION=$ANDROID_API_LEVEL

      - name: Build project
        run: |
          make -j$(nproc)
          make apk INSTALL_ROOT=build

      - name: Prepare signing
        if: ${{ secrets.KEY_STORE_PASSWORD != '' }}
        run: |
          mkdir -p signing
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > signing/app.keystore
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" > signing/keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> signing/keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> signing/keystore.properties



      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: |
            app-release.apk
            build/android-build/build/outputs/apk/release/android-build-release-unsigned.apk
