name: Qt6 Android CI (Universal)

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  QT_VERSION: "6.6.3"
  QT_ARCH: "android_arm64_v8a"  # 明确指定架构
  NDK_VERSION: "26.1.10909125"  # NDK r26b
  ANDROID_API_LEVEL: "34"
  JAVA_VERSION: "17"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # 1. 安装 JDK 17
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      # 2. 安装 Android NDK (精确版本)
      - name: Install NDK
        run: |
          $ndkUrl = "https://dl.google.com/android/repository/android-ndk-r26b-windows.zip"
          Invoke-WebRequest -Uri $ndkUrl -OutFile "ndk.zip"
          Expand-Archive -Path "ndk.zip" -DestinationPath "$env:GITHUB_WORKSPACE\android-sdk\ndk"
          Rename-Item "$env:GITHUB_WORKSPACE\android-sdk\ndk\android-ndk-r26b" "$env:GITHUB_WORKSPACE\android-sdk\ndk\$env:NDK_VERSION"
          echo "ANDROID_NDK_ROOT=$env:GITHUB_WORKSPACE\android-sdk\ndk\$env:NDK_VERSION" >> $env:GITHUB_ENV
          echo "$env:ANDROID_NDK_ROOT\prebuilt\windows-x86_64\bin" >> $env:GITHUB_PATH

      # 3. 使用 jurplel/install-qt-action 安装 Qt 和模块
      - name: Install Qt Android
        uses: jurplel/install-qt-action@v3
        id: qt-android
        with:
          version: ${{ env.QT_VERSION }}
          target: android
          arch: ${{ env.QT_ARCH }}
          modules: qtcharts qtsensors qtlocation qtpositioning qt5compat
          install-dir: ${{ github.workspace }}/Qt

      # 4. 配置环境变量
      - name: Setup Environment
        run: |
          echo "QT_PATH=${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/${{ env.QT_ARCH }}" >> $env:GITHUB_ENV
          echo "${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/${{ env.QT_ARCH }}/bin" >> $env:GITHUB_PATH

          # 生成 gradle.properties 解决兼容性警告
          echo "android.suppressUnsupportedCompileSdk=${{ env.ANDROID_API_LEVEL }}" > gradle.properties

      # 5. 验证工具链
      - name: Verify Tools
        run: |
          qmake --version
          make --version
          java --version

      # 6. 构建项目
      - name: Build
        shell: cmd
        env:
          ANDROID_NDK_ROOT: ${{ github.workspace }}\android-sdk\ndk\${{ env.NDK_VERSION }}
          ANDROID_SDK_ROOT: ${{ github.workspace }}\android-sdk
        run: |
          qmake Knot.pro -spec android-clang CONFIG+=release ANDROID_ABIS=arm64-v8a
          make -j %NUMBER_OF_PROCESSORS%
          make apk INSTALL_ROOT=build

      # 7. 上传APK产物
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Knot-APK
          path: |
            build\android-build\build\outputs\apk\release\*.apk
            build\android-build\build\outputs\apk\debug\*.apk
