name: Qt6 Android CI

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  QT_VERSION: "6.6.3"
  QT_ARCH: "android_arm64_v8a"
  NDK_VERSION: "26.1.10909125"
  ANDROID_API_LEVEL: "34"
  JAVA_VERSION: "17"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: 'src'

      # 1. 安装 JDK
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      # 2. 安装 NDK
      - name: Install NDK
        run: |
          $ndkUrl = "https://dl.google.com/android/repository/android-ndk-r26b-windows.zip"
          Invoke-WebRequest -Uri $ndkUrl -OutFile "ndk.zip"
          Expand-Archive -Path "ndk.zip" -DestinationPath "android-sdk\ndk"
          Rename-Item -Path "android-sdk\ndk\android-ndk-r26b" -NewName $env:NDK_VERSION
          echo "ANDROID_NDK_ROOT=$env:GITHUB_WORKSPACE\android-sdk\ndk\$env:NDK_VERSION" >> $env:GITHUB_ENV
          echo "$env:ANDROID_NDK_ROOT\prebuilt\windows-x86_64\bin" >> $env:GITHUB_PATH

      # 3. 安装 Qt (修复：移除--verbose，升级aqtinstall，验证目录存在性)
      - name: Install Qt
        run: |
          # 升级aqtinstall到最新版本，避免参数兼容问题
          python -m pip install --upgrade aqtinstall

          # 移除--verbose，兼容所有版本；确保模块正确
          aqt install-qt windows android $env:QT_VERSION $env:QT_ARCH `
            -m qt5compat qtbase qtandroidextras qttools `
            --outputdir "$env:GITHUB_WORKSPACE\Qt"

          # 先验证Qt根目录是否存在（核心检查，避免后续无效步骤）
          $qtRoot = "$env:GITHUB_WORKSPACE\Qt\$env:QT_VERSION\$env:QT_ARCH"
          if (!(Test-Path $qtRoot)) {
              echo "::error::Qt安装失败，目录不存在：$qtRoot"
              # 输出Qt安装根目录内容，排查是否有其他版本或路径错误
              dir "$env:GITHUB_WORKSPACE\Qt\$env:QT_VERSION"
              exit 1
          }

          # 再验证bin目录和qmake6.exe
          $qtBin = "$qtRoot\bin"
          echo "=== Qt bin目录内容 ==="
          dir "$qtBin"

          $qmakeExePath = "$qtBin\qmake6.exe"
          if (!(Test-Path $qmakeExePath)) {
              echo "::error::未找到qmake6.exe，安装不完整！"
              exit 1
          } else {
              $size = (Get-Item $qmakeExePath).Length
              echo "qmake6.exe存在（大小：$size字节）"
          }

      # 4. 修正qmake.bat路径
      - name: 修正qmake.bat路径
        run: |
          $qtBin = "$env:GITHUB_WORKSPACE\Qt\$env:QT_VERSION\$env:QT_ARCH\bin"
          $qmakeBatPath = "$qtBin\qmake.bat"

          @"
          @echo off
          "%~dp0qmake6.exe" -qtconf "%~dp0target_qt.conf" %*
          "@ | Out-File -FilePath $qmakeBatPath -Encoding ASCII

          echo "=== 修正后的qmake.bat内容 ==="
          Get-Content $qmakeBatPath

      # 5. 验证安装
      - name: Verify Installation
        run: |
          $qtBin = "$env:GITHUB_WORKSPACE\Qt\$env:QT_VERSION\$env:QT_ARCH\bin"

          if (!(Test-Path "$qtBin\qmake6.exe")) {
              echo "::error::未找到qmake6.exe!"
              exit 1
          }
          if (!(Test-Path "$qtBin\qmake.bat")) {
              echo "::error::未找到qmake.bat!"
              exit 1
          }

          echo "尝试执行qmake6.exe --version:"
          & "$qtBin\qmake6.exe" --version
          if ($LASTEXITCODE -ne 0) {
              echo "::error::qmake6.exe执行失败!"
              exit 1
          }

          echo "尝试执行qmake.bat --version:"
          & "$qtBin\qmake.bat" --version
          if ($LASTEXITCODE -ne 0) {
              echo "::error::qmake.bat执行失败!"
              exit 1
          }

          echo "qmake验证通过"

      # 6. 构建项目
      - name: Build
        shell: cmd
        run: |
          set QT_ROOT=%GITHUB_WORKSPACE%\Qt\%QT_VERSION%\%QT_ARCH%
          set PATH=%QT_ROOT%\bin;%PATH%

          echo "当前路径: %CD%"
          echo "QT_ROOT: %QT_ROOT%"

          echo "=== 查找qmake6.exe ==="
          where qmake6.exe || (
              echo "::error::无法定位qmake6.exe!"
              exit 1
          )

          echo "=== 执行qmake6.exe ==="
          cd src
          "%QT_ROOT%\bin\qmake6.exe" Knot.pro -spec android-clang CONFIG+=release ANDROID_ABIS=arm64-v8a -qtconf "%QT_ROOT%\bin\target_qt.conf"
          if errorlevel 1 (
              echo "::error::qmake执行失败!"
              exit 1
          )

          echo "=== 检查Makefile ==="
          if not exist Makefile (
              echo "::error::Makefile未生成!"
              dir
              exit 1
          )

          echo "=== 开始编译 ==="
          make -j %NUMBER_OF_PROCESSORS%
          if errorlevel 1 (
              echo "::error::编译失败!"
              exit 1
          )

          echo "=== 打包APK ==="
          make apk INSTALL_ROOT=build
          if errorlevel 1 (
              echo "::error::APK打包失败!"
              exit 1
          )

      # 7. 上传产物
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Knot-APK
          path: build\android-build\build\outputs\apk\release\*.apk
