name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  QT_VERSION: "6.6.3"
  QT_ARCH: "android_arm64_v8a"
  ANDROID_API_LEVEL: "34"
  NDK_VERSION: "25.2.9519653"  # 使用更稳定的NDK 25
  BUILD_TOOLS_VERSION: "34.0.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgl1-mesa-dev unzip

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android NDK
        run: |
          mkdir -p android-sdk/ndk
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip -d android-sdk/ndk/
          mv android-sdk/ndk/android-ndk-r25b android-sdk/ndk/${{ env.NDK_VERSION }}
          echo "ANDROID_NDK_ROOT=$GITHUB_WORKSPACE/android-sdk/ndk/${{ env.NDK_VERSION }}" >> $GITHUB_ENV

      - name: Verify NDK
        run: |
          echo "NDK路径: $ANDROID_NDK_ROOT"
          ls -la $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aarch64-linux-android/bits/

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          target: android
          arch: ${{ env.QT_ARCH }}
          modules: qt5compat qtcharts qtsensors qtlocation qtpositioning qtwebview

      - name: Configure project
        run: |
          TOOLCHAIN_PATH="$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64"

          # 使用更简单的参数配置
          qmake Knot.pro \
            -spec android-clang \
            CONFIG+=release \
            ANDROID_ABIS=arm64-v8a \
            ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT \
            ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT \
            QMAKE_CC=$TOOLCHAIN_PATH/bin/aarch64-linux-android$ANDROID_API_LEVEL-clang \
            QMAKE_CXX=$TOOLCHAIN_PATH/bin/aarch64-linux-android$ANDROID_API_LEVEL-clang++ \
            ANDROID_MIN_SDK_VERSION=$ANDROID_API_LEVEL

      - name: Build project
        run: |
          make -j$(nproc)
          make apk INSTALL_ROOT=build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: build/android-build/build/outputs/apk/release/android-build-release-unsigned.apk
