name: Qt6 Android CI (Fixed Paths)

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  QT_VERSION: "6.6.3"
  QT_ARCH: "android_arm64_v8a"
  NDK_VERSION: "26.1.10909125"
  ANDROID_API_LEVEL: "34"
  JAVA_VERSION: "17"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: 'Knot'  # 明确设置检出目录

      # 1. 安装 JDK
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      # 2. 安装 NDK
      - name: Install NDK
        run: |
          $ndkUrl = "https://dl.google.com/android/repository/android-ndk-r26b-windows.zip"
          Invoke-WebRequest -Uri $ndkUrl -OutFile "$env:GITHUB_WORKSPACE\ndk.zip"
          Expand-Archive -Path "$env:GITHUB_WORKSPACE\ndk.zip" -DestinationPath "$env:GITHUB_WORKSPACE\android-sdk\ndk"
          Rename-Item "$env:GITHUB_WORKSPACE\android-sdk\ndk\android-ndk-r26b" "$env:GITHUB_WORKSPACE\android-sdk\ndk\$env:NDK_VERSION"
          echo "ANDROID_NDK_ROOT=$env:GITHUB_WORKSPACE\android-sdk\ndk\$env:NDK_VERSION" >> $env:GITHUB_ENV
          echo "$env:ANDROID_NDK_ROOT\prebuilt\windows-x86_64\bin" >> $env:GITHUB_PATH

      # 3. 安装 Qt（严格匹配日志路径）
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        id: qt-install
        with:
          version: ${{ env.QT_VERSION }}
          target: android
          arch: ${{ env.QT_ARCH }}
          modules: qt5compat
          install-dir: 'D:\a\Knot\Qt'  # 硬编码匹配日志路径

      # 4. 环境配置（使用绝对路径）
      - name: Setup Environment
        run: |
          # 硬编码Qt路径（与安装日志完全一致）
          $qtRoot = "D:\a\Knot\Qt\$env:QT_VERSION\$env:QT_ARCH"
          echo "QT_ROOT=$qtRoot" >> $env:GITHUB_ENV
          echo "$qtRoot\bin" >> $env:GITHUB_PATH

          # 详细验证Qt安装
          echo "=== Qt安装验证 ==="
          echo "检查目录: $qtRoot"
          dir "$qtRoot"
          echo "检查bin目录:"
          dir "$qtRoot\bin" || echo "::error::bin目录不存在!"
          echo "qmake是否存在:"
          Test-Path "$qtRoot\bin\qmake.exe" || echo "::error::qmake.exe不存在!"

      # 5. 构建项目
      - name: Build
        shell: cmd
        env:
          ANDROID_NDK_ROOT: D:\a\Knot\android-sdk\ndk\${{ env.NDK_VERSION }}
          ANDROID_SDK_ROOT: D:\a\Knot\android-sdk
        run: |
          echo "=== 当前工作目录 ==="
          cd
          dir

          echo "=== 查找qmake ==="
          where qmake
          dir "D:\a\Knot\Qt\$env:QT_VERSION\$env:QT_ARCH\bin"

          echo "=== 执行qmake ==="
          "D:\a\Knot\Qt\%QT_VERSION%\%QT_ARCH%\bin\qmake" Knot.pro -spec android-clang CONFIG+=release ANDROID_ABIS=arm64-v8a

          echo "=== 生成的Makefile ==="
          type Makefile || (
            echo "::error::Makefile未生成!"
            dir
            exit 1
          )

          echo "=== 开始编译 ==="
          make -j %NUMBER_OF_PROCESSORS%

          echo "=== 打包APK ==="
          make apk INSTALL_ROOT=build

      # 6. 上传产物
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Knot-APK
          path: build\android-build\build\outputs\apk\release\*.apk
