name: Fcitx5 Qt6 Build (Stable)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      BUILD_ROOT: /opt/fcitx5
      FCITX_VERSION: 5.1.0
      QT_VERSION: 6.6.3

    steps:
    # ================= 环境初始化 =================
    - name: Prepare environment
      run: |
        sudo mkdir -p $BUILD_ROOT
        sudo chown -R runner:runner $BUILD_ROOT

    # ================= 安装系统CMake =================
    - name: Install system tools
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          cmake \
          build-essential \
          ninja-build

    # ================= 安装Qt（绕过版本问题） =================
    - name: Install Qt
      working-directory: ${{ env.BUILD_ROOT }}
      run: |
        pip install aqtinstall
        python -m aqt install-qt linux desktop $QT_VERSION \
          --outputdir qt

        # 验证Qt安装
        [ -f "qt/$QT_VERSION/gcc_64/bin/qmake" ] || exit 1

    # ================= 获取源码 =================
    - name: Get source code
      working-directory: ${{ env.BUILD_ROOT }}
      run: |
        wget https://github.com/fcitx/fcitx5-qt/archive/refs/tags/$FCITX_VERSION.tar.gz
        tar -xzf $FCITX_VERSION.tar.gz
        mv fcitx5-qt-$FCITX_VERSION src

    # ================= 构建配置（关键修复） =================
    - name: Configure build
      working-directory: ${{ env.BUILD_ROOT }}/src/qt6/platforminputcontext
      env:
        Qt6_DIR: ${{ env.BUILD_ROOT }}/qt/$QT_VERSION/gcc_64/lib/cmake/Qt6
      run: |
        mkdir -p build
        cd build

        # 使用系统CMake + 路径修正
        cmake .. \
          -DCMAKE_PREFIX_PATH="$Qt6_DIR" \
          -DCMAKE_BUILD_TYPE=Release \
          -DQT_QMAKE_EXECUTABLE="${{ env.BUILD_ROOT }}/qt/$QT_VERSION/gcc_64/bin/qmake" \
          -Wno-dev

        # 生成构建信息
        cmake --version
        cat CMakeCache.txt | grep Qt6

    # ================= 编译与验证 =================
    - name: Build plugin
      working-directory: ${{ env.BUILD_ROOT }}/src/qt6/platforminputcontext/build
      run: |
        cmake --build . --target fcitx5platforminputcontextplugin -- -j$(nproc)

        # 二进制验证
        file libfcitx5platforminputcontextplugin.so
        ldd libfcitx5platforminputcontextplugin.so | grep -i qt6

    # ================= 上传产物 =================
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fcitx5-qt6-plugin
        path: ${{ env.BUILD_ROOT }}/src/qt6/platforminputcontext/build/libfcitx5platforminputcontextplugin.so
