name: Fcitx5 Qt6 Isolation Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      BUILD_ROOT: /opt/fcitx5
      FCITX_VERSION: 5.1.0
      QT_VERSION: 6.6.3

    steps:
    # ================= 初始化隔离环境 =================
    - name: Prepare environment
      run: |
        sudo mkdir -p $BUILD_ROOT
        sudo chown -R runner:runner $BUILD_ROOT
        echo "BUILD_DIR=$BUILD_ROOT" >> $GITHUB_ENV

    # ================= 安装Qt（修复路径） =================
    - name: Install Qt
      working-directory: ${{ env.BUILD_ROOT }}  # 确保在此目录执行
      run: |
        pip install aqtinstall
        python -m aqt install-qt linux desktop $QT_VERSION \
          --outputdir qt
        echo "QT_PATH=$BUILD_ROOT/qt/$QT_VERSION/gcc_64" >> $GITHUB_ENV

    # ================= 获取源码（精确路径控制） =================
    - name: Download and extract source
      working-directory: ${{ env.BUILD_ROOT }}
      run: |
        wget https://github.com/fcitx/fcitx5-qt/archive/5.1.0.tar.gz
        tar -xzf 5.1.0.tar.gz
        mv fcitx5-qt-5.1.0 src
        ls src/qt6/platforminputcontext/CMakeLists.txt  # 严格验证

    # ================= 构建配置（路径修复） =================
    - name: Configure build
      working-directory: ${{ env.BUILD_ROOT }}/src/qt6/platforminputcontext  # 完整路径
      run: |
        mkdir -p build
        cd build
        cmake .. \
          -DCMAKE_PREFIX_PATH="${{ env.QT_PATH }}" \
          -DCMAKE_BUILD_TYPE=Release \
          -DENABLE_QT6=ON

    # ================= 编译与验证 =================
    - name: Build plugin
      working-directory: ${{ env.BUILD_ROOT }}/src/qt6/platforminputcontext/build
      run: |
          export PATH="${{ env.QT_PATH }}/bin:$PATH"
          cmake --build . --target fcitx5platforminputcontextplugin -- VERBOSE=1

    # ================= 上传产物 =================
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fcitx5-qt6-plugin
        path: ${{ env.BUILD_ROOT }}/src/qt6/platforminputcontext/build/libfcitx5platforminputcontextplugin.so
