name: Optimized Qt6 Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
    - name: Install Qt via aqt
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip install aqtinstall
        aqt install-qt linux desktop 6.6.3 --outputdir ~/Qt
        echo "QT_PATH=~/Qt/6.6.3/gcc_64" >> $GITHUB_ENV

    - name: Build Fcitx5
      run: |
        git clone --depth 1 --branch 5.1.0 \
          https://github.com/fcitx/fcitx5-qt.git \
          fcitx5-qt
        mkdir build && cd build
        cmake .. \
          -DCMAKE_PREFIX_PATH="${{ env.QT_PATH }}" \
          -DCMAKE_INSTALL_PREFIX=./output \
          -DCMAKE_BUILD_TYPE=Release \
          -DENABLE_QT4=OFF \
          -DENABLE_QT6=ON
        cmake --build . --target fcitx5platforminputcontextplugin -- -j$(nproc)
        objdump -T libfcitx5platforminputcontextplugin.so | grep Qt6Core  # 验证链接

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: fcitx5-plugin
        path: fcitx5/plugins/platforminputcontext/build/*.so
