name: Fixed Fcitx5 Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      QT_VER: 6.6.3
      SRC_DIR: ${{ github.workspace }}/fcitx5-qt

    steps:
    # ================= 环境准备 =================
    - name: Check workspace
      run: |
        echo "Workspace path: ${{ github.workspace }}"
        ls -la ${{ github.workspace }}

    # ================= 安装 Qt =================
    - name: Install Qt via aqt
      run: |
        pip install aqtinstall
        aqt install-qt linux desktop $QT_VER \
          --outputdir ~/Qt
        echo "QT_PATH=~/Qt/$QT_VER/gcc_64" >> $GITHUB_ENV

    # ================= 获取源码 =================
    - name: Clone repository
      run: |
        git clone --depth 1 --branch 5.1.0 \
          https://github.com/fcitx/fcitx5-qt.git \
          $SRC_DIR
        
        # 验证源码结构
        ls -l $SRC_DIR/CMakeLists.txt
        ls -l $SRC_DIR/platforminputcontext/CMakeLists.txt

    # ================= 构建配置 =================
    - name: Configure build
      working-directory: ${{ env.SRC_DIR }}/platforminputcontext
      run: |
        mkdir build && cd build
        cmake .. \
          -DCMAKE_PREFIX_PATH="${{ env.QT_PATH }}" \
          -DCMAKE_BUILD_TYPE=Release \
          -DENABLE_QT6=ON \
          -Wno-dev
        
        # 生成构建树可视化
        cmake --graphviz=graph.dot .
        dot -Tpng graph.dot -o build-graph.png

    # ================= 编译验证 =================
    - name: Build and verify
      working-directory: ${{ env.SRC_DIR }}/platforminputcontext/build
      run: |
        cmake --build . --target fcitx5platforminputcontextplugin -- -j$(nproc)
        
        # 二进制文件验证
        file libfcitx5platforminputcontextplugin.so
        nm -D libfcitx5platforminputcontextplugin.so | grep -i qt6

    # ================= 产物处理 =================
    - name: Archive output
      uses: actions/upload-artifact@v4
      with:
        name: fcitx5-qt6-artifacts
        path: |
          ${{ env.SRC_DIR }}/platforminputcontext/build/libfcitx5platforminputcontextplugin.so
          ${{ env.SRC_DIR }}/platforminputcontext/build/build-graph.png
