name: Fcitx5 Qt6 Fixed Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      BUILD_ROOT: /opt/fcitx5
      QT_VERSION: 6.6.3

    steps:
    # ================= 初始化环境 =================
    - name: Setup environment
      run: |
        sudo mkdir -p $BUILD_ROOT
        sudo chown -R runner:runner $BUILD_ROOT

    # ================= 安装核心依赖 =================
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git cmake ninja-build \
          extra-cmake-modules \
          libkf5coreaddons-dev \
          libxkbcommon-dev \
          libdbus-1-dev

    # ================= 安装 Qt =================
    - name: Install Qt
      working-directory: ${{ env.BUILD_ROOT }}
      run: |
        pip install aqtinstall
        aqt install-qt linux desktop $QT_VERSION --outputdir qt
        echo "QT_PATH=$BUILD_ROOT/qt/$QT_VERSION/gcc_64" >> $GITHUB_ENV

    # ================= 获取源码并修复 =================
    - name: Clone and patch source
      working-directory: ${{ env.BUILD_ROOT }}
      run: |
        git clone --depth 1 https://github.com/fcitx/fcitx5-qt.git src

        # 修复 CMakeLists.txt
        sed -i '1i cmake_minimum_required(VERSION 3.16 FATAL_ERROR)\nfind_package(ECM REQUIRED)\ninclude(ECM)\ninclude(ECMSetupVersion)\nset(PROJECT_VERSION "5.1.0")\necm_setup_version(PROJECT\n  VARIABLE_PREFIX FCITX5\n  VERSION ${PROJECT_VERSION}\n  SOVERSION 5\n)' src/qt6/platforminputcontext/CMakeLists.txt

    # ================= 配置构建 =================
    - name: Configure build
      working-directory: ${{ env.BUILD_ROOT }}/src/qt6/platforminputcontext
      env:
        ECM_DIR: /usr/share/ECM/cmake
      run: |
        mkdir -p build && cd build
        cmake .. \
          -DCMAKE_PREFIX_PATH="$QT_PATH;$ECM_DIR" \
          -DQT_QMAKE_EXECUTABLE="$QT_PATH/bin/qmake" \
          -DCMAKE_BUILD_TYPE=Release

    # ================= 编译与验证 =================
    - name: Build plugin
      working-directory: ${{ env.BUILD_ROOT }}/src/qt6/platforminputcontext/build
      run: |
        cmake --build . --target fcitx5platforminputcontextplugin -- -j$(nproc)
        ldd libfcitx5platforminputcontextplugin.so | grep -i qt6

    # ================= 上传产物 =================
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fcitx5-qt6-plugin
        path: ${{ env.BUILD_ROOT }}/src/qt6/platforminputcontext/build/libfcitx5platforminputcontextplugin.so
