name: Fcitx5 Qt6 Build (Stable)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      BUILD_ROOT: /opt/fcitx5
      FCITX_VERSION: 5.1.0
      QT_VERSION: 6.6.3

    steps:
    # ================= 环境初始化 =================
    - name: Prepare environment
      run: |
        sudo mkdir -p $BUILD_ROOT
        sudo chown -R runner:runner $BUILD_ROOT

    # ================= 安装系统CMake =================
    - name: Install system tools
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          cmake \
          build-essential \
          ninja-build

    - name: Install ECM
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          extra-cmake-modules \
          libkf5coreaddons-dev

    # ================= 安装Qt（绕过版本问题） =================
    - name: Install Qt
      working-directory: ${{ env.BUILD_ROOT }}
      run: |
        pip install aqtinstall
        python -m aqt install-qt linux desktop $QT_VERSION \
          --outputdir qt

        # 验证Qt安装
        [ -f "qt/$QT_VERSION/gcc_64/bin/qmake" ] || exit 1

    # ================= 获取源码 =================
    - name: Get source code
      working-directory: ${{ env.BUILD_ROOT }}
      run: |
        wget https://github.com/fcitx/fcitx5-qt/archive/refs/tags/$FCITX_VERSION.tar.gz
        tar -xzf $FCITX_VERSION.tar.gz
        mv fcitx5-qt-$FCITX_VERSION src

    # ================= 构建配置（关键修复） =================
    - name: Configure build (Final Fix)
      working-directory: ${{ env.BUILD_ROOT }}/src/qt6/platforminputcontext
      env:
        QMAKE_PATH: ${{ env.BUILD_ROOT }}/qt/6.6.3/gcc_64/bin
      run: |
        # 验证 qmake 可执行性
        ls -l $QMAKE_PATH/qmake
        $QMAKE_PATH/qmake --version

        # 配置构建参数
        cmake .. \
          -DCMAKE_PREFIX_PATH="${{ env.BUILD_ROOT }}/qt/6.6.3/gcc_64" \
          -DQT_QMAKE_EXECUTABLE="$QMAKE_PATH/qmake" \
          -DCMAKE_BUILD_TYPE=Release \
          -DENABLE_QT6=ON

        # 显示 Qt 配置信息
        grep Qt6_DIR CMakeCache.txt

    # ================= 编译与验证 =================
    - name: Build plugin
      working-directory: ${{ env.BUILD_ROOT }}/src/qt6/platforminputcontext/build
      run: |
        cmake --build . --target fcitx5platforminputcontextplugin -- -j$(nproc)

        # 二进制验证
        file libfcitx5platforminputcontextplugin.so
        ldd libfcitx5platforminputcontextplugin.so | grep -i qt6

    # ================= 上传产物 =================
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fcitx5-qt6-plugin
        path: ${{ env.BUILD_ROOT }}/src/qt6/platforminputcontext/build/libfcitx5platforminputcontextplugin.so
