name: Build Fcitx5 Qt6 Plugin

on: [push]  # 可通过API触发

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Setup Qt 6.6.3
      run: |
        # 安装Qt6.6.3
        QT_INSTALLER_URL="https://download.qt.io/official_releases/qt/6.6/6.6.3/qt-unified-linux-x64-6.6.3-online.run"
        wget -O qt-installer.run "$QT_INSTALLER_URL"
        chmod +x qt-installer.run
        echo "yes" | ./qt-installer.run \
          --accept-license \
          --skip-components *x11* *web* *quick* *3d* *tools* *translations* \
          --components qt.base,qt.qt6.6.3.qtbase,qt.qt6.6.3.qttools \
          --install-dir $HOME/Qt/6.6.3/gcc_64

    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          cmake \
          ninja-build \
          g++ \
          libxcb1-dev \
          libxkbcommon-dev \
          libxcb-xinerama0-dev \
          libxcb-util-dev \
          libgl1-mesa-dev \
          libfontconfig1-dev \
          libfreetype6-dev

    - name: Clone Fcitx5 source
      run: |
        git clone https://code.qt.io/fcitx5/fcitx5.git
        cd fcitx5
        git checkout 6a6b3d3  # 2023-03-15的稳定提交

    - name: Configure build
      working-directory: fcitx5/plugins/platforminputcontext
      run: |
        mkdir build && cd build
        cmake .. \
          -DCMAKE_PREFIX_PATH="$HOME/Qt/6.6.3/gcc_64" \
          -DCMAKE_INSTALL_PREFIX=./install \
          -DCMAKE_BUILD_TYPE=Release

    - name: Compile plugin
      working-directory: fcitx5/plugins/platforminputcontext/build
      run: cmake --build . --target fcitx5platforminputcontextplugin

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fcitx5-plugin
        path: fcitx5/plugins/platforminputcontext/build/install/lib/libfcitx5platforminputcontextplugin.so
