name: MacOS-Universal
on:
  push:
    branches: [main]
    paths:
      - '**.pro'
      - '!stats.txt'
      - '!README.md'
  pull_request:
    paths:
      - '**'
  release:
    types: [published]

jobs:
  build:
    name: Build-Universal
    runs-on: macos-14
    permissions:
      contents: write
    env:
      targetName: Knot
      VERSION: Mac-Universal
      orgName: Knot
      QT_VERSION: 6.10.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt Universal
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.10.3
          cached: 'false'
          host: mac
          target: desktop
          arch: universal
          install-deps: true
          source: false
          dir: ${{ github.workspace }}/Qt/6.10.3/universal

      - name: Dual Homebrew arm64 + x86_64
        run: |
          if [ ! -d "/opt/homebrew" ]; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi
          echo '/opt/homebrew/bin' >> $GITHUB_PATH
          if [ ! -d "/usr/local/Homebrew" ]; then
            arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi
          echo '/usr/local/bin' >> $GITHUB_PATH
          source ~/.zshrc

      - name: Install OpenSSL two arch
        run: |
          brew update && brew install openssl && brew link --force openssl
          arch -x86_64 brew update && arch -x86_64 brew install openssl && arch -x86_64 brew link --force openssl

      - name: Build Universal Binary
        run: |
          unset ARCHFLAGS CFLAGS CXXFLAGS LDFLAGS
          export PATH=${{ github.workspace }}/Qt/6.10.3/universal/bin:$PATH
          qmake "CONFIG += release" "QMAKE_APPLE_DEVICE_ARCHS=x86_64 arm64"
          make -j$(sysctl -n hw.ncpu)

      - name: Clone macdeployqtfix
        run: git clone https://github.com/tamlok/macdeployqtfix.git macdeployqtfix --depth=1

      - name: Package App & DMG
        run: |
          cp -f ExtBin/mac/Info.plist bin/release/${targetName}.app/Contents/Info.plist
          cp -R -p -f bin/release/${targetName}.app ${targetName}.app
          macdeployqt ${targetName}.app -qmldir=. -verbose=1 -always-overwrite
          python3 ./macdeployqtfix/macdeployqtfix.py ./${targetName}.app/Contents/MacOS/${targetName} ${{ github.workspace }}/Qt/6.10.3/universal
          hdiutil create -volname "${targetName}" -srcfolder ${targetName}.app -ov -format UDZO ${targetName}-universal.dmg
          cp ${targetName}-universal.dmg bin/release/

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.orgName }}-${{ env.VERSION }}
          path: bin/release/${{ env.targetName }}-universal.dmg

      - name: Upload Release Asset
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/release/${{ env.targetName }}-universal.dmg
          asset_name: ${{ env.orgName }}-${{ env.VERSION }}.dmg
          tag: ${{ github.ref_name }}
          overwrite: true